name: JACKRABBIT
favicon: null
layout_spectrum: 0.08140230155549943
typography_spectrum: 0.4126049515325576
title: JACKRABBIT Body Care
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1d23'
    - '#fefcf0'
    - '#f6d091'
    - '#c6935a'
    - '#a36e46'
  brandStrength: 0.41966940416023135
  lightness: 0.6074649377260357
  saturation: 0.09458382125012577
  rhythmicContrast: 0.3196244623977691
purpose: []
