name: JACKRABBIT
favicon: null
layout_spectrum: 0.08140230155549943
typography_spectrum: 0.4126049515325576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.41966940416023135
  lightness: 0.6074649377260357
  saturation: 0.09458382125012577
  rhythmicContrast: 0.3196244623977691
purpose: []
